DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Course_Course;
DROP TABLE IF EXISTS CourseResult;
DROP TABLE IF EXISTS DataSourceConfig;
DROP TABLE IF EXISTS Employee_Courses;
DROP TABLE IF EXISTS SemesterResult;
DROP TABLE IF EXISTS Student_Courses;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS User_SemesterResult;

DROP SEQUENCE IF EXISTS hibernate_sequence;
CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE Course (
    id BIGINT NOT NULL,
    courseCode VARCHAR(255),
    courseDescription VARCHAR(255),
    courseTitle VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE Course_Course (
    Course_id BIGINT NOT NULL,
    prerequisites_id BIGINT NOT NULL,
    PRIMARY KEY (Course_id, prerequisites_id)
);

CREATE TABLE CourseResult (
    id BIGINT NOT NULL,
    courseId BIGINT,
    examScore INTEGER NOT NULL,
    passScore INTEGER NOT NULL,
    studentId VARCHAR(255),
    testScore INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE DataSourceConfig (
    id VARCHAR(255) NOT NULL,
    driverClassName VARCHAR(255),
    initialize BOOLEAN NOT NULL,
    name VARCHAR(255),
    password VARCHAR(255),
    url VARCHAR(255),
    username VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE Employee_Courses (
    employee_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL
);

CREATE TABLE SemesterResult (
    id BIGINT NOT NULL,
    cgpa INTEGER NOT NULL,
    gpa INTEGER NOT NULL,
    level INTEGER NOT NULL,
    passScore INTEGER NOT NULL,
    scores BINARY(255),
    semester INTEGER NOT NULL,
    student_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE Student_Courses (
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL
);

CREATE TABLE User (
    DTYPE VARCHAR(31) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    password VARCHAR(255),
    pic BINARY(255),
    role INTEGER,
    username VARCHAR(255),
    employeeId VARCHAR(255),
    dept VARCHAR(255),
    level VARCHAR(255),
    matricNo VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE User_SemesterResult (
    Student_id BIGINT NOT NULL,
    results_id BIGINT NOT NULL
);

ALTER TABLE Course_Course
    ADD CONSTRAINT UK_r8t47id6esiwylv8bilahm979 UNIQUE (prerequisites_id);

ALTER TABLE User_SemesterResult
    ADD CONSTRAINT UK_3ft9gx8tnu8g0orthofopy1sd UNIQUE (results_id);

ALTER TABLE Course_Course
    ADD CONSTRAINT FK1vcis9htunykmab5emskt7m3o
    FOREIGN KEY (prerequisites_id) REFERENCES Course;

ALTER TABLE Course_Course
    ADD CONSTRAINT FK1amdcikwwhxkqbqnlsctpx7fi
    FOREIGN KEY (Course_id) REFERENCES Course;

ALTER TABLE Employee_Courses
    ADD CONSTRAINT FKnvaxynby14i58x547ubr79rf0
    FOREIGN KEY (course_id) REFERENCES Course;

ALTER TABLE Employee_Courses
    ADD CONSTRAINT FKl4hdatfv9jrl4qt1esthsi19o
    FOREIGN KEY (employee_id) REFERENCES User;

ALTER TABLE SemesterResult
    ADD CONSTRAINT FKgurrd33kaib0a30jx13r47a52
    FOREIGN KEY (student_id) REFERENCES User;